force-app/main/default/objects/Gift_Aid_Claim__c/Gift_Aid_Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used for linked all gift aid claims against</description>
    <label>Gift Aid Claim</label>
    <nameField>
        <displayFormat>GACID-{000000000}</displayFormat>
        <label>Gift Aid Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Aid_Configuration__c/Gift_Aid_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>These are the custom settings for GiftAid within the salesforce</description>
    <label>Gift Aid Configuration</label>
</CustomObject>

force-app/main/default/objects/Gift_Aid_Configuration__c/fields/Primary_Contact_Field__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Field__c</fullName>
    <defaultValue>&#39;Gift_Aid_Contact__c&#39;</defaultValue>
    <inlineHelpText>Please provide the API Name of the field on your opportunity that determines who the primary contact for the opportunity is</inlineHelpText>
    <label>Primary Contact Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Declaration__c/Gift_Aid_Declaration__c.object-meta.xml
<CustomObject>
    <description>This object is used for storing a record of the contacts gift aid declaration in.</description>
    <label>Gift Aid Declaration</label>
    <nameField>
        <displayFormat>GADID-{000000000}</displayFormat>
        <label>Gift Aid Declaration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Declarations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Aid_Declaration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This confirms if the GAD is active or not</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Declaration__c/fields/Active_date__c.field-meta.xml
<CustomField>
    <fullName>Active_date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>This is the date the GAD was made active</inlineHelpText>
    <label>Active date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Declaration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the contact this declaration is for</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Gift Aid Declarations</relationshipLabel>
    <relationshipName>Gift_Aid_Declarations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Declaration__c/fields/In_Active_date__c.field-meta.xml
<CustomField>
    <fullName>In_Active_date__c</fullName>
    <inlineHelpText>This is the date the GAD was deactivated</inlineHelpText>
    <label>In Active date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Declaration__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>This was the source for this declaration</inlineHelpText>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GAD_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gift_Aid_Claim__c.field-meta.xml
<CustomField>
    <fullName>Gift_Aid_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Gift Aid Claim this is related to</inlineHelpText>
    <label>Gift Aid Claim</label>
    <referenceTo>Gift_Aid_Claim__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/GAD_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Verbal</fullName>
    </customValue>
    <customValue>
        <fullName>Written</fullName>
    </customValue>
    <description>This determines where the Gift Aid Declaration came from</description>
    <masterLabel>GAD Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GAC_Helper.cls
/**
 * @description     helper methods used within contacts and opportunities
 * @author          daniel@hyphen8.com
 * @date            30/06/2020
 * @groups          Helpers
 */
public with sharing class GAC_Helper {
    
    /**
     * @description     aura enabled method to check if a contact has an active Gift Aid Declaration
     * @param           string recordId
     * @return          Gift_Aid_Declaration__c
     */
    @AuraEnabled
    public static Gift_Aid_Declaration__c getGiftAidDeclaration(string recordId){
        try {
            return [SELECT ID, Active_Date__c, Source__c FROM Gift_Aid_Declaration__c WHERE Contact__c=:recordId AND Active__c = true LIMIT 1];
        } catch (Exception e){
            return null;
        }
    }


    /**
     * @description     aura enabled method that will deactivate the current contacts GAD
     * @param           string recordId
     * @return          string
     */
    @AuraEnabled
    public static string deactiveActiveGAD(string recordId){
        Gift_Aid_Declaration__c gad = [SELECT ID, Active__c, In_Active_date__c FROM Gift_Aid_Declaration__c WHERE ID=:recordId LIMIT 1];
        gad.In_Active_date__c = system.today();
        gad.Active__c = false;
        try {
            update gad;
            return 'Success';
        } catch (Exception e){
            string errorMessage = e.getMessage();
            return errorMessage;
        }
        
    }


    /**
     * @description     method  used when a new GAD is inserted and has Find Previous Donations selected
     * @param           Map<ID, ID> mapOfContactToGADs
     * @param           Set<ID> setOfContactIDs
     */
    public static void processHistoricOpportunities(Map<ID, ID> mapOfContactToGADs, Set<ID> setOfContactIDs){

        Gift_Aid_Configuration__c gacSettings = Gift_Aid_Configuration__c.getOrgDefaults();
        string contactField = gacSettings.Primary_Contact_Field__c;
        string nullvalue = null;
        string query = 'SELECT ID, Gift_Aid_Declaration__c, ' + contactField + ' FROM Opportunity WHERE ' + contactField + ' IN: setOfContactIDs AND Gift_Aid_Claim__c=:nullvalue';
        List<Opportunity> listOfOpportunities = Database.query(query);
        system.debug('listOfOpportunities > ' + listOfOpportunities);
        
        List<Opportunity> listOfOpportunitiesToUpdate = new List<Opportunity>();

        for(Opportunity opportunity:listOfOpportunities){
            string contactID = (string)opportunity.get(contactField);
            ID gadID = mapOfContactToGADs.get(contactID);
            opportunity.Gift_Aid_Declaration__c = gadID;
            listOfOpportunitiesToUpdate.add(opportunity);
        }

        database.update(listOfOpportunitiesToUpdate);
    }

    /**
     * @description     method used when a GAD is made inactive and opportuntities are still availalbe for claiming
     * @param           Set<ID> setOfGADIDs
     */
    public static void closeOffUnclaimedOpportunities(Set<ID> setOfGADIDs){

        List<Opportunity> listOfOpportunities = [SELECT ID, Gift_Aid_Declaration__c FROM Opportunity WHERE (Gift_Aid_Claim_Status__c=:'New' OR Gift_Aid_Claim__c=:null) AND Gift_Aid_Declaration__c IN:setOfGADIDs];

        List<Opportunity> listOfOpportunitiesToUpdate = new List<Opportunity>();

        for(Opportunity opportunity:listOfOpportunities){
            opportunity.Gift_Aid_Declaration__c = null;
            opportunity.Gift_Aid_Claim__c = null;
            listOfOpportunitiesToUpdate.add(opportunity);
        }

        database.update(listOfOpportunitiesToUpdate);
    }

    /**
     * @description     method to get gift aid settings
     * @return          boolean
     */
    public static Gift_Aid_Configuration__c getGacSettings(){
        Gift_Aid_Configuration__c gacSettings = Gift_Aid_Configuration__c.getOrgDefaults();
        return gacSettings;
    }


    /**
     * @description     get a map of Gift Aid Declarations based on current contacts
     * @param           Set<ID> contactIds
     * @return          Map<ID, ID> mapOfContactGADs
     */
    public static Map<ID, ID> getMapOfContactGADs(Set<ID> contactIds){
        List<Gift_Aid_Declaration__c> listOfGADs = [SELECT ID, Contact__c FROM Gift_Aid_Declaration__c WHERE Contact__c IN:contactIds AND Active__c=:true];
        Map<ID, ID> mapOfContactGADs = new Map<ID, ID>();
        for(Gift_Aid_Declaration__c gad:listOfGADs){
            mapOfContactGADs.put(gad.Contact__c, gad.Id);
        }
        return mapOfContactGADs;
    }
}