force-app/main/default/objects/Gift_Aid_Claim__c/Gift_Aid_Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used for linked all gift aid claims against</description>
    <label>Gift Aid Claim</label>
    <nameField>
        <displayFormat>GACID-{000000000}</displayFormat>
        <label>Gift Aid Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Aid_Claim__c/fields/Claim_Amount__c.field-meta.xml
<CustomField>
    <fullName>Claim_Amount__c</fullName>
    <inlineHelpText>This is the amount within this claim</inlineHelpText>
    <label>Claim Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This is the status of Gift Aid Claim</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gift_Aid_Claim__c.field-meta.xml
<CustomField>
    <fullName>Gift_Aid_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Gift Aid Claim this is related to</inlineHelpText>
    <label>Gift Aid Claim</label>
    <referenceTo>Gift_Aid_Claim__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GAC_Rollup_BATCH.cls
/**
 * @description     batch rollup class for performing an aggregated result against a gift aid claim
 * @author          daniel@hyphen8.com
 * @date            20/04/2020
 * @group           Rollups
*/
public class GAC_Rollup_BATCH implements Database.Batchable<sObject>{
    
    /**
     * @description     The querylocation within the batch class to find claims that need have their rollups run
     * @param           Database.BatchableContext BC
     */
    public Database.QueryLocator start(Database.BatchableContext BC){
        string allowedstatus = 'New';
        String query = 'SELECT Id,Claim_Amount__c FROM Gift_Aid_Claim__c WHERE Status__c=allowedstatus ';
        return Database.getQueryLocator(query);
    }

    /**
     * @description     the execution process for this batch class
     * @param           Database.BatchableContext BC
     * @param           List<Gift_Aid_Claim__c gacs
    */
    public void execute(Database.BatchableContext BC, List<Gift_Aid_Claim__c> gacs){
        List<Gift_Aid_Claim__c> gaClaims = new List<Gift_Aid_Claim__c>();
        for( Gift_Aid_Claim__c gac : gacs){
            AggregateResult[] claimedAmountOpps = [SELECT Sum(Amount)total FROM Opportunity WHERE Gift_Aid_Claim__c=:gac.Id];
            Object claimAmountObject = claimedAmountOpps[0].get('total');
            decimal claimAmount = 0;
            if(claimAmountObject!=null){
                claimAmount = (decimal)claimAmount;
            }
            gac.Claim_Amount__c = claimAmount;
            gaClaims.add(gac);
        }
        update gaClaims;
    }

    /**
     * @description     this is the finish method on this batch class just output a debug log of what has happened
     * @param           Database.Batchable BC
     */
    public void finish(Database.BatchableContext BC){}
}