force-app/main/default/objects/Gift_Aid_Claim__c/Gift_Aid_Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used for linked all gift aid claims against</description>
    <label>Gift Aid Claim</label>
    <nameField>
        <displayFormat>GACID-{000000000}</displayFormat>
        <label>Gift Aid Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Aid_Claim__c/fields/Claim_start_date__c.field-meta.xml
<CustomField>
    <fullName>Claim_start_date__c</fullName>
    <defaultValue>today()</defaultValue>
    <inlineHelpText>This is the date this claim is from</inlineHelpText>
    <label>Claim start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Configuration__c/Gift_Aid_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>These are the custom settings for GiftAid within the salesforce</description>
    <label>Gift Aid Configuration</label>
</CustomObject>

force-app/main/default/objects/Gift_Aid_Configuration__c/fields/Claim_back_year__c.field-meta.xml
<CustomField>
    <fullName>Claim_back_year__c</fullName>
    <defaultValue>4</defaultValue>
    <inlineHelpText>This is the number of years prior that you can go back an apply for giftaid from a tax payer.</inlineHelpText>
    <label>Claim back year</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Configuration__c/fields/GAC_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>GAC_Review_Status__c</fullName>
    <defaultValue>&#39;In Review&#39;</defaultValue>
    <inlineHelpText>Use this to define what the internal review status is for your organisation</inlineHelpText>
    <label>GAC Review Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Configuration__c/fields/Gift_Aid_Confirmation_Field__c.field-meta.xml
<CustomField>
    <fullName>Gift_Aid_Confirmation_Field__c</fullName>
    <defaultValue>&#39;Giftable_Record__c&#39;</defaultValue>
    <inlineHelpText>This is a field a checkbox on your Opportunity / Income record that is used to determine if the related contact has confirmed if they pay tax.</inlineHelpText>
    <label>Gift Aid Confirmation Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Configuration__c/fields/Gift_Aid_Rate__c.field-meta.xml
<CustomField>
    <fullName>Gift_Aid_Rate__c</fullName>
    <inlineHelpText>This is the GiftAid % to be applied to an income/donation record</inlineHelpText>
    <label>Gift Aid Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Configuration__c/fields/Months_between_claims__c.field-meta.xml
<CustomField>
    <fullName>Months_between_claims__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Use this to define how frequently a Gift Aid Claim should be created. This will automatically set the end date for a claim and create a new one when that time is up.</inlineHelpText>
    <label>Months between claims</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Configuration__c/fields/Primary_Contact_Field__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Field__c</fullName>
    <defaultValue>&#39;Gift_Aid_Contact__c&#39;</defaultValue>
    <inlineHelpText>Please provide the API Name of the field on your opportunity that determines who the primary contact for the opportunity is</inlineHelpText>
    <label>Primary Contact Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Configuration__c/fields/Process_Gift_Aid__c.field-meta.xml
<CustomField>
    <fullName>Process_Gift_Aid__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Use this to turn on or off the gift aid processes if set to true then it will be active</inlineHelpText>
    <label>Process Gift Aid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gift_Aid_Configuration__c/fields/Send_batch_completion_email__c.field-meta.xml
<CustomField>
    <fullName>Send_batch_completion_email__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Use this to confirm if when the daily batch runs we should send a completion notification</inlineHelpText>
    <label>Send batch completion email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gift_Aid_Claim__c.field-meta.xml
<CustomField>
    <fullName>Gift_Aid_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Gift Aid Claim this is related to</inlineHelpText>
    <label>Gift Aid Claim</label>
    <referenceTo>Gift_Aid_Claim__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gift_Aid_Contact__c.field-meta.xml
<CustomField>
    <fullName>Gift_Aid_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the contact we are processing gift aid for</inlineHelpText>
    <label>Gift Aid Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Giftable_Record__c.field-meta.xml
<CustomField>
    <fullName>Giftable_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This tick box is used to confirm that this record can have gift aid applied to it</inlineHelpText>
    <label>Giftable Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GA_DataFactory.cls
/**
 * @description     DataFactory class for supporting with the creation of data for testing
 * @author          daniel@hyphen8.com
 * @date            19/04/2020
 * @group           Tests
*/
@isTest
public with sharing class GA_DataFactory {
    
    /**
     * @description     in memory is used to confirm if we should be creating the records or just returing them
    */
    public static boolean inMemory;

    /**
     * @description     method to create our custom setting
     * @return          Gift_Aid_Configuration__c
    */
    public static Gift_Aid_Configuration__c createGiftAidConfiguration(){
        Gift_Aid_Configuration__c gacCS = new Gift_Aid_Configuration__c();
        gacCs.Claim_back_year__c = 4;
        gacCS.GAC_Review_Status__c = 'In Review';
        gacCS.Gift_Aid_Rate__c = 25;
        gacCS.Months_between_claims__c = 1;
        gacCS.Process_Gift_Aid__c = true;
        gacCS.Send_batch_completion_email__c = true;
        gacCS.Primary_Contact_Field__c = 'Gift_Aid_Contact__c';
        gacCS.Gift_Aid_Confirmation_Field__c = 'Giftable_Record__c';

        if(!inMemory){
            insert gacCS;
        }
        return gacCS;
    }

    
    /**
     * @description     create a user
     * @param           ID profileid
     * @param           string firstName
     * @param           string lastName
     * @return          User
    */
    public static User createUser(id profileid, string firstName, string lastName){
        String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+randomId; 
        User user = new User(
            FirstName = firstName,
            LastName = lastName, 
            Email = uniqueName + '@test' + orgId + '.org', 
            Username = uniqueName + '@test' + orgId + '.org', 
            EmailEncodingKey = 'ISO-8859-1', 
            Alias = uniqueName.substring(18, 23), 
            TimeZoneSidKey = 'GMT',  
            LocaleSidKey = 'en_GB', 
            LanguageLocaleKey = 'en_US', 
            ProfileId  = profileid); 
        if(!inMemory){
            insert user;
        }
        return user;
    }

    /**
     * @description     create an Account
     * @param           string name of the Account
     * @return          Account
    */
    public static Account createAccount(string name){
        Account account = new Account(Name=name);
        if(!inMemory){
            insert account;
        }
        return account;
    }

    /**
     * @description     create a Contact
     * @param           string accountId for the Account we are linking the contact to
     * @param           string firstName
     * @param           string lastName
     * @return          Contact
    */
    public static Contact createContact(string accountId, string firstName, string lastName){
        Contact contact = new Contact(FirstName=firstName, LastName=lastName, AccountID=accountid);
        if(!inMemory){
            insert contact;
        }
        return contact;
    }

    /**
     * @description     create a Gift Aid Claim
     * @param           date startDate
     * @return          Gift_Aid_Claim__c
    */
    public static Gift_Aid_Claim__c createGiftAidClaim(date startDate){
        Gift_Aid_Claim__c giftAidClaim = new Gift_Aid_Claim__c(Claim_start_date__c=startDate);
        if(!inMemory){
            insert giftAidClaim;
        }
        return giftAidClaim;
    }

    /**
     * @description     create an Opportunity record
     * @param           string oppName
     * @param           string accountId
     * @param           date closeDate
     * @param           string stageName
     * @param           decimal amount
     * @param           string gacId
     * @return          Opportunity
    */
    public static Opportunity createOpportunity(string oppName, string accountId, date closeDate, string stageName, decimal amount, string gacId){
        Opportunity opportunity = new Opportunity(Name=oppName,AccountId=accountId,CloseDate=closeDate,StageName=stageName,Amount=amount, Gift_Aid_Claim__c=gacId);
        if(!inMemory){
            insert opportunity;
        }
        return opportunity;
    }

    /**
     * @description     create a list Opportunities 
     * @param           string oppName
     * @param           string accountId
     * @param           date closeDate
     * @param           string stageName
     * @param           decimal amount
     * @param           string gacId
     * @param           integer noOfOpportunities
     * @return          List<Opportunity>
    */
    public static List<Opportunity> createOpportunityList(string oppName, string accountId, date closeDate, string stageName, decimal amount, string gacId, integer noOfOpportunities){
        List<Opportunity> listOfOpportunity = new List<Opportunity>();
        for(Integer i=0;i<noOfOpportunities;i++) {
            Opportunity opportunity = new Opportunity(Name=oppName + ' ' + i,AccountId=accountId,CloseDate=closeDate,StageName=stageName,Amount=amount, Gift_Aid_Claim__c=gacId);
            listOfOpportunity.add(opportunity);
        }
        if(!inmemory){
            insert listOfOpportunity;
        }
        return listOfOpportunity;
    }

}